#pragma once

enum CGIVar {
	CONTENT_LENGTH = 0,
	DOCUMENT_ROOT,
	HTTP_REFERER,
	HTTP_USER_AGENT,
	PATH_INFO,
	PATH_TRANSLATED,
	QUERY_STRING,
	REMOTE_ADDR,
	REMOTE_HOST,
	REQUEST_METHOD,
	REQUEST_URI,
	SCRIPT_FILENAME,
	SCRIPT_NAME,
	SERVER_NAME,
	SERVER_PORT,
	SERVER_PROTOCOL,
	CGIVar_Count
};

const char *CGIVarName[]; // defined in HTTPRequest.cpp